services:
  website:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: npm start